### ISSUE TITLE
Dan needs a bagel

### ISSUE THREAD

**Issue by rodluger** [dfm/exoplanet#13]
With lox cream cheese.

**Comment by rodluger** [comment]
![image](https://user-images.githubusercontent.com/9323819/49739521-1984e580-fc60-11e8-8664-cade4a84dd0c.png)

**Comment by rodluger** [comment]
@megbedell

**Comment by megbedell** [comment]
I nominate this for the logo

**Comment by megbedell** [comment]
![bagel](https://user-images.githubusercontent.com/13722237/49740115-864caf80-fc61-11e8-9b93-fef867913edc.png)
#8

**Comment by rodluger** [comment]
Dan approves!

**Comment by dfm** [comment]
Ping #8

**Comment by barentsen** [comment]
Can I have a donut?

**Comment by dfm** [comment]
u can haz waffle:

![523653661524741652](https://user-images.githubusercontent.com/350282/49825996-cd1ad200-fd53-11e8-9ea1-cd30594643e5.jpg)

**Comment by barentsen** [comment]
Fine.
