### ISSUE TITLE
Use analytic solution to quartic equation when solving for contact points

### ISSUE THREAD

**Issue by dfm** [dfm/exoplanet#17]
A suggestion from @ericagol. See the appendix of [Kipping (2008)](https://arxiv.org/abs/0807.0096).

**Comment by ericagol** [comment]
This paper may also be useful:

https://arxiv.org/abs/1811.05484

**Comment by dfm** [comment]
Absolutely - Thanks!

**Comment by dfm** [comment]
Another quartic solver: https://www.sciencedirect.com/science/article/pii/S0377042710002128

**Comment by dfm** [comment]
I've now incorporated a special purpose quartic solver using companion matrices and it seems pretty robust and efficient. I'm going to table this for now.
