### ISSUE TITLE
jitter not used in example 51 Peg fit?

### ISSUE THREAD

**Issue by megbedell** [dfm/exoplanet#19]
In the example of [fitting 51 Peg data with exoplanet](https://exoplanet.dfm.io/en/latest/tutorials/intro-to-pymc3/#a-more-realistic-example-radial-velocity-exoplanets), there's a log-jitter variable defined, but I don't see where it comes into the fit.

My guess on how to fix this is that you should change from 
`pm.Normal("obs", mu=rvmodel, sd=rv_err, observed=rv)` 
to 
`pm.Normal("obs", mu=rvmodel, sd=tt.sqrt(tt.sqr(rv_err) + s2), observed=rv)`.
Is that ok, or does there need to be a penalty term in the likelihood function for large jitter explicitly defined also? Or am I misunderstanding what's happening here entirely??

**Comment by dfm** [comment]
Yep - that should be included and your suggested syntax is right! Thanks!

I think it's done correctly in [the RV tutorial](https://exoplanet.dfm.io/en/latest/tutorials/rv/), but I missed it here.

**Comment by dfm** [comment]
Fixed. Thanks!
