### ISSUE TITLE
K2-24 tutorial does not converge

### ISSUE THREAD

**Issue by mrtommyb** [dfm/exoplanet#22]
I did a fresh conda environment and installed exoplanet and dependencies. I ran the K2-24 tutorial in a downloaded notebook and I get the following from the sample
```python
with model:

    trace = sampler.sample(draws=2000)

Sampling 4 chains: 100%|██████████| 8000/8000 [00:37<00:00, 215.91draws/s]
ERROR:pymc3:The chain contains only diverging samples. The model is probably misspecified.
WARNING:pymc3:The acceptance probability does not match the target. It is 0.0, but should be close to 0.9. Try to increase the number of tuning steps.
ERROR:pymc3:There were 1999 divergences after tuning. Increase `target_accept` or reparameterize.
WARNING:pymc3:The acceptance probability does not match the target. It is 9.77952587176284e-17, but should be close to 0.9. Try to increase the number of tuning steps.
ERROR:pymc3:There were 1907 divergences after tuning. Increase `target_accept` or reparameterize.
WARNING:pymc3:The acceptance probability does not match the target. It is 0.006233605808817455, but should be close to 0.9. Try to increase the number of tuning steps.
ERROR:pymc3:There were 1918 divergences after tuning. Increase `target_accept` or reparameterize.
WARNING:pymc3:The acceptance probability does not match the target. It is 6.736254608770937e-15, but should be close to 0.9. Try to increase the number of tuning steps.
ERROR:pymc3:The gelman-rubin statistic is larger than 1.4 for some parameters. The sampler did not converge.
ERROR:pymc3:The estimated number of effective samples is smaller than 200 for some parameters.
```
The summary output is similarly bad
```python

  | mean | sd | mc_error | hpd_2.5 | hpd_97.5 | n_eff | Rhat
-- | -- | -- | -- | -- | -- | -- | --
42.363591 | 0.000301 | 0.000030 | 42.363218 | 42.364071 | NaN | 7.343693
20.885450 | 0.000205 | 0.000021 | 20.885138 | 20.885673 | 2.018893 | 12.642319
0.063015 | 0.000591 | 0.000059 | 0.062178 | 0.063959 | NaN | 6.166608
0.046068 | 0.000590 | 0.000059 | 0.045105 | 0.046691 | 2.028321 | 10.391917
29.863008 | 2.787906 | 0.278459 | 25.333686 | 33.197244 | 2.035109 | 8.949308
24.414847 | 2.274746 | 0.227115 | 22.034980 | 28.812748 | NaN | 3.937818
0.119697 | 0.069082 | 0.006903 | 0.004913 | 0.187045 | 2.018684 | 12.257648
0.228654 | 0.043500 | 0.004344 | 0.166656 | 0.279087 | NaN | 9.578997
0.575165 | 0.042205 | 0.004219 | 0.522428 | 0.645138 | NaN | 7.824198
0.607800 | 0.057467 | 0.005744 | 0.519003 | 0.679079 | 2.014646 | 13.941053
```

**Comment by mrtommyb** [comment]
I ran the transit.ipynb tutorial and there were no problems.

**Comment by mrtommyb** [comment]
I pip installed version 0.1.2 and the issues are gone. I would guess that the problems are related to the changes made in bce2019d7045cc87fed73adb8f3e3633b86e4a4b

**Comment by dfm** [comment]
Thanks Tom. I'm looking into this now. I'm not sure that that's the change that's causing the problem but I'll figure it out. Can you post your version of the notebook as a gist or something so that I can take a look?

**Comment by mrtommyb** [comment]
Sure, added to https://github.com/mrtommyb/l98-59-transitmodel/blob/master/code/together.ipynb

**Comment by dfm** [comment]
Thanks! This looks like something wrong with how the sampler works after tuning because everything looks good until then. I'll play around with this and see what I can do.

**Comment by dfm** [comment]
So I have confirmed that it is a bug in the sampler, but I haven't been able to track it down. In the meantime, here is a workaround. Replace:

```python
with model:
    trace = sampler.sample(draws=2000)
```

with

```python
with model:
    start, step = sampler._get_start_and_step()
    step = pm.NUTS(potential=step.potential, target_accept=0.9)
    trace = pm.sample(draws=2000, tune=200, step=step, start=start)
```

**Comment by mrtommyb** [comment]
thanks Dan. I switch to an earlier commit and it seems to be working fine (I'm running on this one 597b2db247ed00b46d5c73a54aaf0c5e0c2e61f0).

**Comment by dfm** [comment]
Just be warned that the definition of impact parameter is wrong for `e != 0`. You should probably use a later commit that includes the updated impact parameter definition or the workaround above. Otherwise your results will be wrong unless you're assuming circular orbits!

**Comment by mrtommyb** [comment]
I ran the updated version of together.ipynb. While things are better, my results are not consistent with yours, e.g. here is a plot.
![screenshot from 2019-01-19 10-17-39](https://user-images.githubusercontent.com/1900573/51428617-b29a0b00-1bd3-11e9-9d11-61b0a152de0c.png)

**Comment by dfm** [comment]
Brutal. What version of pymc3 are you on?

**Comment by mrtommyb** [comment]
I verified that it's just a single chain that's going wonky.

**Comment by dfm** [comment]
Thanks! I'm still on PyMC3.5. I'll take a look at what changed.

**Comment by dfm** [comment]
I've made a few updates to how the sampler works and everything in the K2-24 seems to be good now. Want to take a look to make sure that it's ok for you with the current github master?

**Comment by mrtommyb** [comment]
I haven't rerun yet, but looking at your updated notebook, the sampling doesn't looks to have been super effective.

**Comment by dfm** [comment]
How so? Here's the most recent run with master: https://github.com/dfm/exoplanet/blob/4ff759822b590ef444d9b338ef61dfa074032d68/docs/_static/notebooks/together.ipynb
Looks great to me! Is there something I'm missing?

**Comment by mrtommyb** [comment]
My mistake, I was accidentally looking at this version
https://github.com/dfm/exoplanet/blob/b2ebd856483fa547408061993e8e67f5e67b2fcd/docs/_static/notebooks/together.ipynb

**Comment by mrtommyb** [comment]
looks good now

**Comment by dfm** [comment]
haha - yes, I did manage to reproduce your issue :-) Thanks!

**Comment by mrtommyb** [comment]
Thanks for fixing things.

**Comment by mrtommyb** [comment]
Unfortunately, I do not seem to be getting the same results are you, and there are convergence problems still. The only difference I can think of is that I'm on theano 1.0.4.
![screenshot from 2019-01-29 21-37-25](https://user-images.githubusercontent.com/1900573/51954469-53779a00-240e-11e9-9bcb-59490c687028.png)
![screenshot from 2019-01-29 21-37-50](https://user-images.githubusercontent.com/1900573/51954468-53779a00-240e-11e9-82f4-186e86721506.png)

**Comment by dfm** [comment]
Just getting back to this and I'm now getting the same problem again. Very strange! It seems to have something to do with omega. It's true that there can be numerical issues with the `Angle` distribution in some edge cases, but that should be vanishingly unlikely and I'm having trouble diagnosing. I'll keep digging and let you know!

**Comment by dfm** [comment]
Ugh - I'm having issues with this again. Disregard for now. I don't understand wtf is going on.

**Comment by dfm** [comment]
After many months of work, I have now gotten to the bottom of this. It was a lot of different factors contributing, but the main thing was instability of the function that computes the times of the contact points for the transit. It's not perfect now, but at least it *knows* when it's wrong now. Here's the most up to date tutorial (you'll see that everything looks good): https://exoplanet.dfm.io/en/latest/tutorials/together/
And I'm about to release v0.1.6 that fixes all this. Let me know if you run into anything else!

**Comment by mrtommyb** [comment]
Great! Thanks Dan. I also notice a big speedup for the planet I'm working with.

**Comment by iancze** [comment]
Strangely enough, I also just ran into this same issue (with 1/4 chains getting stuck, though for a 28 parameter fit to a triple star, not a transiting exoplanet system). Turns out I am on theano v1.0.4 as well, though I arrived here by default after a fresh conda install a few days ago. Will try an updated theano version.

**Comment by dfm** [comment]
This definitely isn't the same problem and probably isn't related to the Theano version. It probably isn't even an exoplanet issue (it's normally something to do with modeling choices), but open a new issue if you can't get it sorted!

**Comment by iancze** [comment]
Thanks for the quick reply! I ran the chains again (exact same model, tuning params, and starting points) and nothing stuck this time. It seems to be somewhat of a transient behavior. 

This did only start happening once I complexified my model with more parameters, so you're probably right that it's something to do with modeling choices.
