### ISSUE TITLE
AttributeError: module 'exoplanet' has no attribute 'optimize'

### ISSUE THREAD

**Issue by hippke** [dfm/exoplanet#23]
I tried the tutorial for [transit fitting](https://exoplanet.dfm.io/en/latest/tutorials/transit/) with exoplanet 0.14dev under Python 3.7 + all latest software. When running `map_soln = xo.optimize(start=model.test_point)` I get the error `AttributeError: module 'exoplanet' has no attribute 'optimize'`

**Comment by dfm** [comment]
You must not actually be using the updated exoplanet. Make sure that you `pip uninstall exoplanet` a few times and then update from GitHub. It has only been added within the past day or so...

**Comment by hippke** [comment]
Thanks. I re-installed from source and now get this:
```
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', GetClOp(TensorConstant{[-1.   0.3  0.2]}), '\n', 'Compilation failed (return status=1): In file included from /home/michael/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-buster-sid-x86_64-3.7.0-64/tmpk3a4zjpg/mod.cpp:7:0:. /home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/exoplanet-0.1.4.dev0-py3.7.egg/exoplanet/theano_ops/starry/include/theano_helpers.h:5:10: fatal error: Eigen/Core: No such file or directory.  #include <Eigen/Core>.           ^~~~~~~~~~~~. compilation terminated.. ', '[GetClOp(TensorConstant{[-1.   0.3  0.2]})]')
```

**Comment by dfm** [comment]
That suggests to me that you didn't recursively clone because Eigen is included in the starry submodule. Try running the following in your git checkout:

```bash
git submodule update --init --recursive
```

and then

```bash
pip uninstall exoplanet
python setup.py develop
```

or

```bash
pip uninstall exoplanet
python setup.py install
```

**Comment by hippke** [comment]
Ah! This last error is only present if numpy==1.16. It runs fine in numpy==1.15. 
Probably worth checking compatibility with different theanos + numpy versions

**Comment by dfm** [comment]
This is a Theano problem (or maybe conda, depending on how you interpret it), not an exoplanet problem. Raise an issue there if you want, but that's not something that this repo will fix!

Note that Theano 1.0.4 is compatible with numpy 1.16 (as tested here: https://travis-ci.org/dfm/exoplanet).
