### ISSUE TITLE
system/environment issue on supercomputer

### ISSUE THREAD

**Issue by Li-Yangyang** [dfm/exoplanet#30]
Hi, 
I am doing unit-test of exoplanet on supercomputer cluster. However I met a problem of system or environment issue about it. It seems about the flag of theano module. Here is the test feedback. Do you have any insight how to configure those possible wrong flag value in the theano backend?
Thanks,
  Yangyang 
[bug_infos.log](https://github.com/dfm/exoplanet/files/2978616/bug_infos.log)

**Comment by dfm** [comment]
The unit tests really only work when executed within the git repository (because of flags, as you say). Did you execute the tests as follows:

```
git clone https://github.com/dfm/exoplanet
cd exoplanet
py.test -v exoplanet
```

If so, can you tell me your Theano, PyMC3 and exoplanet versions?

**Comment by Li-Yangyang** [comment]
I just redid the test under git repository, still not passing. Theano: 1.0.4, PyMC3: 3.6, exoplanet: 0.1.5

**Comment by dfm** [comment]
Looking more closely, it looks like the error is coming from the fact that your system isn't exposing a c++ compiler. It looks like you'll need to set the `cxx` theano flag to point to your c++ compiler. All the ops in exoplanet are implemented in C so it won't work without this! Let me know how that goes.

**Comment by Li-Yangyang** [comment]
Many thanks. One more thing about the unit-test of exoplanet is that it seems that c++ compiler can not find Eigen3 and starry lib. After I added them to my system lib directory and point cxx to the c++ complier, unit-test worked. Therefore if possible, a brief guidance about that two lib configuration might be added to the testing part of exoplanet documentation.

Regards,
  Yangyang

**Comment by dfm** [comment]
This means that you didn't follow the docs and git clone --recursive :).
I'm not sure that adding to the docs helps if it isn't followed... ;)

On Thu, Mar 21, 2019 at 5:26 PM Li-Yangyang <notifications@github.com>
wrote:

> Many thanks. One more thing about the unit-test of exoplanet is that it
> seems that c++ compiler can not find Eigen3 and starry lib. After I added
> them to my system lib directory and point cxx to the c++ complier,
> unit-test worked. Therefore if possible, a brief guidance about that two
> lib configuration might be added to the testing part of exoplanet
> documentation.
>
> Regards,
> Yangyang
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dfm_exoplanet_issues_30-23issuecomment-2D475409051&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=Lynx-ffOXTSNiqexqdNSgca1IjeO87GzguIBr_sWmMM&s=hrtDZNuwVUQP_fHYHEVDYVJnrpkjjnUYwuf-4bxTgtM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAVYSrxclFv7lsFUSSfmoW3K7jQDsK-5FNks5vY-5FkXgaJpZM4b56a-5F&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=Lynx-ffOXTSNiqexqdNSgca1IjeO87GzguIBr_sWmMM&s=AgCu2u2mNaaKQlxvR4UnCnh14BWUK4SOwwQ-agTzW3E&e=>
> .
>
-- 
Dan Foreman-Mackey
Associate Research Scientist
Flatiron Institute
http://dfm.io

**Comment by Li-Yangyang** [comment]
Oh, yeah! I just followed the "git clone" suggestions and didn't check the doc lol. Alright, that works if add --recursive. Still many thanks. It's perfect time to close this issue. :)

Regards,
Yangyang
