### ISSUE TITLE
Planetary coordinate system in multi-planet case

### ISSUE THREAD

**Issue by ericagol** [dfm/exoplanet#50]
@dfm  In the multi-planet case, in which coordinate system do you solve Kepler's equations?  The ideal is to use Jacobi coordinates, although heliocentric and barycentric are easier to implement.  However, both heliocentric and barycentric have drawbacks.

**Comment by dfm** [comment]
I'm not sure if I totally understand the question, but the code treats the system as a sum of independent two body orbits with a single primary body. Each of these orbits can then be solved in heliocentric or barycentric frames. Does that make sense? Feedback appreciated!

**Comment by ericagol** [comment]
Yes, that makes sense, and is probably the easiest way to go.
