### ISSUE TITLE
Hacking exoplanet to fit two disparate transits without "islands" in the period PDF...

### ISSUE THREAD

**Issue by hposborn** [dfm/exoplanet#59]
For a few transiting systems (and increasingly more with the gaps likely to occur in TESS) we have two individual transits that are separated by a long gap, meaning we have no real knowledge of the orbital period except for a few discrete integer period ratios. These create "islands" in the posteriors and make MCMC modelling extremely difficult... The most well known such case is HIP 41378 (https://arxiv.org/abs/1809.10688).
I'm trying to come up with a (probably hacky) way that exoplanet can model such systems without converging on only a single period island... Any ideas would be appreciated.

- The least hacky method is to simply force a model to converge on each of the N period "islands" and compute an evidence (or BIC) for each... Which is obviously not simple with an MCMC compared to, say, PyMultiNest.

- An easier way (and the way I probably have hope of coding) might be to model each transit separately and find the intersection of the posteriors, but I feel like we're losing information (and certainly efficiency) by treating each transit as independent.

- Another relatively easy way would be to fit two t0s for each transit and offset the second dataset such that they overlap (i.e. the model sees two sets of transits at t0...), while leaving the period continuous. But this seems annoying to model with a GP and I'm not sure how exoplanet/PyMC works with a parameter directly modifying the input data..?

- A final way might be to, instead of modelling a period, model some time difference plus a scalar integer period ratio (eg (t_1-t_0)/n where n={1,2,3,4,...,max}). This would seem to be the best solution. But I don't know if using non-continuous variables is implementable and/or differentiable as PyMC requires?

Any ideas which of these options seems most reasonable, and also how simple it might be to hack exoplanet to fit them?

**Comment by dfm** [comment]
This is an interesting question!

I'd probably consider implementing it using a version of your last proposal, but analytically marginalizing over `n`. I'd probably fit for a parameter `p0` then compute the full model for each value of `period = p0 / n` for `n = ...`. Then you can just sum over the likelihoods (not the log likelihoods!) to compute the marginalized likelihood.

It might be better to move this conversation to email and we can try to work it out there.

**Comment by dfm** [comment]
Here's a demonstration of this method in practice: https://gist.github.com/dfm/122a184be253ead0466c424cf3932b5d
