### ISSUE TITLE
better eccentricity distribution?

### ISSUE THREAD

**Issue by megbedell** [dfm/exoplanet#61]
Currently the orbit-fitting tutorials use xo.distributions.UnitUniform or Uniform as a prior for orbital eccentricity, but this can bias the resulting maximum-likelihood estimate to high e. Are there plans to add any built-in distributions that would make better priors on eccentricity? One option might be a beta-distribution ([Kipping 2014](https://ui.adsabs.harvard.edu/abs/2014MNRAS.444.2263K/abstract)).

**Comment by megbedell** [comment]
OK, that's fair. Thanks! I'd consider this issue resolved.

**Comment by dfm** [comment]
I do think that leaving this open and providing a few named options is worth considering.

I know of [Kipping 2014](https://ui.adsabs.harvard.edu/abs/2014MNRAS.444.2263K/abstract) and [Van Eylen et al 2019](https://ui.adsabs.harvard.edu/abs/2019AJ....157...61V/abstract), but there must be other ones that should be included.

**Comment by dfm** [comment]
Or rather [Kipping 2013](https://ui.adsabs.harvard.edu/abs/2013MNRAS.434L..51K/abstract).

**Comment by dfm** [comment]
Helper functions for both of these distributions are now implemented:

https://exoplanet.dfm.io/en/latest/user/api/#eccentricity-distributions
