### ISSUE TITLE
Add limbdark citation when it's submitted

### ISSUE THREAD

**Issue by dfm** [dfm/exoplanet#7]

**Comment by dfm** [comment]
What's our status @rodluger @ericagol?

**Comment by ericagol** [comment]
Getting closer!  @rodluger  has created a module, made a rough-draft of the documents, and created a Julia package.  I've been working on fixing some mislabeling in a figure which I discovered last night, and adding some documentation strings.

**Comment by dfm** [comment]
Awesome!
